# Generated by Django 4.2.27 on 2026-03-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_address_userprofile_employment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='experience',
            field=models.PositiveIntegerField(blank=True, help_text='Years of experience', null=True),
        ),
    ]
