# Generated by Django 4.2.27 on 2026-01-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loanapplication_remarks_loanapplication_reviewed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='extra_details',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
